language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+android-card-form@getbraintree.com
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository
script: ./gradlew clean lint test
