language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+android-card-form@getbraintree.com
sudo: false
android:
  components:
    - platform-tools
    - tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-support
    - extra-android-m2repository
env:
  global:
    - TERM=dumb
script: ./gradlew --info clean lint test
